### ISSUE TITLE
Dissociating Resources

### ISSUE THREAD

**Issue by tcholoss** [opentelekomcloud-docs/cloud-backup-recovery#44]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-backup-recovery/blob/main/api-ref/source/cbr_apis/vaults/dissociating_resources.rst

I've found an issue with the Documentation on this page about Cloud Backup and Recovery Dissociating Resources.
The example request is not correct:
Example Requests

POST https://{endpoint}/v3/f841e01fd2b14e7fa41b6ae7aa6b0594/vaults/79bd9daa-884f-4f84-b8fe-235d58cd927d/associatepolicy

{
  "resource_ids" : [ "97595625-198e-4e4d-879b-9d53f68ba551" ]
}

Instead of /associatepolicy it should be /removeresources.

Please correct this, so it won't be misleading for others.

Thank you in advance!

**Comment by jmiskani** [comment]
The documentation has been updated, thank you for reporting the issue
